version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/postgres:9.6
        environment:
        - POSTGRES_USER=circleci
        - POSTGRES_DB=circleci
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install postgresql-client git-lfs
            git lfs install
      - run:
          name: Checkout binaries
          command: git lfs pull
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Setup database
          command: psql --host localhost --file db/test/postgresql/init.sql
      - run:
          name: Configure build - jdbc conf file
          command: cp src/main/resources/jdbc.properties.example src/main/resources/jdbc.properties
      - run:
          name: Configure build - security conf file
          command: cp src/main/resources/security.properties.example src/main/resources/security.properties
      - run:
          name: Configure build - odk-settings conf file
          command: cp src/main/resources/odk-settings.xml.example src/main/resources/odk-settings.xml
      # breaking up the commands prevents out of memory errors on CircleCI
      - run: ./gradlew check
      - run: ./gradlew war
      - save_cache:
          paths:
            - ~/.gradle
            - ~/work/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: build/libs
          destination: libs
      - store_test_results:
          path: build/test-results
